### ISSUE TITLE
[Bug反馈]错别字和目录中含有空格导致无法解析的问题

### ISSUE THREAD

**Issue by HolyGu** [SydneyOwl/shx8800-config-editor#6]
版本信息：shx8800-config-editor-release_windows_amd64.exe
操作系统版本：Windows 11 22H2

第一个是软件有个错别字，虽然不影响使用就是看着有点难受
![image](https://github.com/SydneyOwl/shx8800-config-editor/assets/28488437/9a02a584-b541-408b-a7d6-48bd80a06022)
![image](https://github.com/SydneyOwl/shx8800-config-editor/assets/28488437/865959a7-5350-48bc-b5c2-f3f5a2a173f6)

第二个是软件在dat文件为绝对路径并且路径含有空格的情况下，会导致解析配置文件失败
![image](https://github.com/SydneyOwl/shx8800-config-editor/assets/28488437/40e2a344-8f24-43f6-843f-f03c2a330afa)

**Comment by SydneyOwl** [comment]
已解决
